on: [push]

name: CI

jobs:
  build_and_test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          target: wasm32-unknown-unknown

      - run: npm install --ci
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: wasm-pack
      - run: make
      - run: npm test

      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: pkg
          path: pkg
